version: "3"
services:
  marketplace:
    image: ldesplanche/marketplace
    restart: always
    ports:
      - 8080:8081
    depends_on:
      - mysql
    environment:
      DB_TYPE: mysql
      DB_DATABASE: marketplace
      DB_USER: marketplace
      DB_PASSWORD: marketplace
      DB_HOST: mysql
      DB_PORT: 3306

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: marketplace
      MYSQL_USER: marketplace
      MYSQL_PASSWORD: marketplace
      MYSQL_ROOT_PASSWORD: marketplace
